version: "3"
services: 
    tweet-worker:
        build: ./tweet-worker
        environment: 
            - DB_URL="postgresql"
            - MQ_URL="rabbitmq"
        networks: 
            - zwitter

    postgres:
        image: postgres:12
        environment: 
            - POSTGRES_PASSWORD=password
        networks: 
            - zwitter
        volumes: 
            - zwitter-vol

volumes:
    zwitter:
networks:
    zwitter: