/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tweet.worker;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;
import com.rabbitmq.tools.json.JSONUtil;

public class App {

    private static final String TWEET_QUEUE = "tweet";

    public static void main(String[] args) throws IOException, TimeoutException {
        System.out.println("Tweet Worker Running...");
        System.out.println("DB URL: " + System.getenv("DB_URL"));
        System.out.println("MQ URL: " + System.getenv("MQ_URL"));

        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("192.168.99.100");
        Connection connection = factory.newConnection();
        Channel channel = connection.createChannel();

        channel.queueDeclare(TWEET_QUEUE, false, false, false, null);
        System.out.println("Listening for tweets");

        DeliverCallback deliverCallback = (consumerTag, delivery) -> {

            String message = new String(delivery.getBody(), "UTF-8");
            System.out.println("Received " + message);
        };

        channel.basicConsume(TWEET_QUEUE, true, deliverCallback, consumerTag -> {
        });
    }
}
